###
http://localhost:5001/client/customers


###
http://localhost:5001/client/transactions

###
http://localhost:5001/client/geography


###
http://localhost:5001/sales/sales

###
http://localhost:5001/general/dashboard


###
http://localhost:5001/management/performance/63701cc1f03239b7f700000e

